name: ci-cd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Compile and test with Maven
        run: mvn clean verify

      - name: Build JAR
        run: mvn package -DskipTests -Djar.finalName=greet-api

      - name: Check if JAR exists
        run: |
          if [ ! -f target/greet-api.jar ]; then
            echo "JAR not found!"
            exit 1
          fi

      - name: Copy files to remote server with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          source: "greet-api.jar"
          target: ${{ secrets.UPLOAD_PATH }}

      - name: Reboot remote application with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd ${{ secrets.UPLOAD_PATH }}
            sudo deploy.sh greet-api.jar
            exit
